# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=102)),
                ('nombre', models.CharField(max_length=102)),
                ('colonia', models.CharField(max_length=102)),
                ('tipo_lugar', models.CharField(max_length=102)),
            ],
        ),
    ]
